sudo: required
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - sudo add-apt-repository ppa:smspillaz/cmake-3.0.2 -y
  - sudo apt-get -qq update
  - sudo apt-get install cmake-3.0.2 -y
  - sudo apt-get install -y ninja-build
  - sudo mkdir -p /usr/local/android-sdk/cmake/bin/
  - sudo ln -s /usr/bin/cmake /usr/local/android-sdk/cmake/bin/cmake